[terminal]
# The VT to run the greeter on. Can be "next", "current" or a number
vt = 1

# The default session, also known as the greeter.
[default_session]
command = "cage -s -mlast -- regreet"
user = "greeter"

[GTK]
application_prefer_dark_theme = true
theme_name = "Orchis-Grey-Dark"
font_name = "Inter Regular 10"
cursor_theme_name = "Notwaita-Gray"
icon_theme_name = "Boston"

[appearance]
greeting_msg = "This worked"
